version: '3'

services:
  database:
    image: mysql:5.7
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "join_db"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
  php-apache:
    container_name: php-apache
    build:
      context: ./.docker/php
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/join
      - ./.docker/php/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - database
